### ISSUE TITLE
traffic-mirroring-how-it-works.md suggested improvements

### ISSUE THREAD

**Issue by cvcrckt** [awsdocs/amazon-traffic-mirroring-guide#1]
In the "Available Traffic Mirroring Configurations" table, "Source Target Type" is ambiguous. It should be "Target Type", right? In which case we also want to see NLB represented, since it is the recommended target type, at least in the product release announcement.

Also, that table covers VPC sharing. It does not cover the fact that a TM target itself can be shared.

**Comment by julieso** [comment]
It was intended to be the source. I removed the column, as the entries were all "network interface".
